fix: ForkTsCheckerWebpackPlugin fails when more than one worker is used
Webpack fails with error:
```
Error: Using typescript incremental compilation API is currently only allowed with a single worker.
```

Use single worker instead.